/* Line numbers in comments correspond to line numbers in input file. 
   To match the numbers of lines in output file, you can find and 
   replace (Notepad++ recommended) following regular expression:
   [^\n]*\|\|[^\n]*\n   with nothing. */

//void test() {
//   int studentId;
//   int* students = NULL;
//   int size;
//   void* DS = Init();
//   AddTeam(DS,2);
//   GetAllStudentsByPower(DS,-1,&students, &size);
//   free(students);
//   students=NULL;
//   AddStudent(DS,337,-2,0);
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   MoveStudentToTeam(DS,942,-3);
//   MoveStudentToTeam(DS,984,1);
//   MoveStudentToTeam(DS,822,1);
//   IncreaseLevel(DS,1,-3);
//   RemoveStudent(DS,834); // 10
//   RemoveStudent(DS,263);
//   IncreaseLevel(DS,1,2);
//   GetMostPowerful(DS,-3,&studentId);
//   MoveStudentToTeam(DS,626,2);
//   RemoveStudent(DS,500);
//   AddTeam(DS,1);
//   AddTeam(DS,-3);
//   AddTeam(DS,-2);
//   GetMostPowerful(DS,1,&studentId);
//   RemoveStudent(DS,327); // 20
//   GetMostPowerful(DS,-1,&studentId);
//   AddStudent(DS,122,-3,2);
//   MoveStudentToTeam(DS,772,2);
//   MoveStudentToTeam(DS,270,-3);
//   MoveStudentToTeam(DS,710,-1);
//   RemoveStudent(DS,643);
//   MoveStudentToTeam(DS,926,3);
//   IncreaseLevel(DS,-1,-1);
//   AddStudent(DS,483,2,-2);
//   GetMostPowerful(DS,-1,&studentId); // 30
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   MoveStudentToTeam(DS,863,-1);
//   RemoveStudent(DS,314);
//   GetAllStudentsByPower(DS,3,&students, &size);
//   free(students);
//   students=NULL;
//   IncreaseLevel(DS,-2,3);
//   AddTeam(DS,2);
//   GetAllStudentsByPower(DS,0,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,1,&studentId);
//   MoveStudentToTeam(DS,924,-2);
//   MoveStudentToTeam(DS,996,0); // 40
//   IncreaseLevel(DS,3,-3);
//   GetAllStudentsByPower(DS,-1,&students, &size);
//   free(students);
//   students=NULL;
//   GetAllStudentsByPower(DS,3,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,1,&studentId);
//   AddStudent(DS,-8,3,1);
//   GetAllStudentsByPower(DS,-3,&students, &size);
//   free(students);
//   students=NULL;
//   IncreaseLevel(DS,1,3);
//   AddStudent(DS,683,2,1);
//   RemoveStudent(DS,440);
//   GetAllStudentsByPower(DS,-2,&students, &size); // 50
//   free(students);
//   students=NULL;
//   MoveStudentToTeam(DS,984,2);
//   AddTeam(DS,2);
//   AddStudent(DS,451,-3,1);
//   AddTeam(DS,-3);
//   GetAllStudentsByPower(DS,1,&students, &size);
//   free(students);
//   students=NULL;
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   AddStudent(DS,742,2,-3);
//   RemoveStudent(DS,149);
//   IncreaseLevel(DS,-2,-1);
//   IncreaseLevel(DS,-3,-3); // 60
//   GetAllStudentsByPower(DS,-1,&students, &size);
//   free(students);
//   students=NULL;
//   IncreaseLevel(DS,0,0);
//   MoveStudentToTeam(DS,872,-1);
//   AddStudent(DS,761,1,1);
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   IncreaseLevel(DS,-1,0);
//   GetMostPowerful(DS,3,&studentId);
//   AddTeam(DS,-3);
//   AddStudent(DS,431,-2,1);
//   GetAllStudentsByPower(DS,2,&students, &size); // 70
//   free(students);
//   students=NULL;
//   IncreaseLevel(DS,-3,2);
//   AddStudent(DS,602,1,-2);
//   IncreaseLevel(DS,-1,2);
//   AddTeam(DS,-1);
//   MoveStudentToTeam(DS,310,-2);
//   RemoveStudent(DS,166);
//   GetMostPowerful(DS,-2,&studentId);
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   IncreaseLevel(DS,0,-3);
//   GetAllStudentsByPower(DS,1,&students, &size); // 80
//   free(students);
//   students=NULL;
//   RemoveStudent(DS,649);
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   MoveStudentToTeam(DS,485,-1);
//   AddStudent(DS,26,-2,-2);
//   IncreaseLevel(DS,-1,3);
//   IncreaseLevel(DS,0,-1);
//   AddTeam(DS,0);
//   AddTeam(DS,2);
//   AddTeam(DS,1);
//   MoveStudentToTeam(DS,415,0); // 90
//   RemoveStudent(DS,508);
//   MoveStudentToTeam(DS,904,-1);
//   GetMostPowerful(DS,1,&studentId);
//   MoveStudentToTeam(DS,434,3);
//   GetMostPowerful(DS,-3,&studentId);
//   MoveStudentToTeam(DS,701,-3);
//   GetAllStudentsByPower(DS,1,&students, &size);
//   free(students);
//   students=NULL;
//   AddStudent(DS,84,-2,-2);
//   GetAllStudentsByPower(DS,3,&students, &size);
//   free(students);
//   students=NULL;
//   MoveStudentToTeam(DS,97,-3); // 100
//   GetMostPowerful(DS,1,&studentId);
//   MoveStudentToTeam(DS,100,1);
//   GetMostPowerful(DS,-1,&studentId);
//   AddStudent(DS,658,2,0);
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   AddStudent(DS,961,0,3);
//   IncreaseLevel(DS,-2,-1);
//   AddStudent(DS,467,-3,0);
//   GetAllStudentsByPower(DS,-1,&students, &size);
//   free(students);
//   students=NULL;
//   GetAllStudentsByPower(DS,-2,&students, &size); // 110
//   free(students);
//   students=NULL;
//   MoveStudentToTeam(DS,861,-3);
//   IncreaseLevel(DS,0,1);
//   MoveStudentToTeam(DS,375,1);
//   AddTeam(DS,-2);
//   MoveStudentToTeam(DS,753,-2);
//   MoveStudentToTeam(DS,426,-1);
//   RemoveStudent(DS,715);
//   AddStudent(DS,658,3,1);
//   MoveStudentToTeam(DS,461,2);
//   AddTeam(DS,1); // 120
//   AddStudent(DS,896,1,2);
//   IncreaseLevel(DS,-3,-2);
//   AddStudent(DS,463,-3,2);
//   AddStudent(DS,35,-1,2);
//   MoveStudentToTeam(DS,635,0);
//   GetMostPowerful(DS,1,&studentId);
//   GetMostPowerful(DS,1,&studentId);
//   RemoveStudent(DS,120);
//   IncreaseLevel(DS,0,2);
//   AddStudent(DS,648,-1,-1); // 130
//   GetMostPowerful(DS,-3,&studentId);
//   MoveStudentToTeam(DS,847,-3);
//   GetAllStudentsByPower(DS,3,&students, &size);
//   free(students);
//   students=NULL;
//   MoveStudentToTeam(DS,676,0);
//   MoveStudentToTeam(DS,617,-2);
//   IncreaseLevel(DS,3,3);
//   RemoveStudent(DS,286);
//   IncreaseLevel(DS,0,2);
//   IncreaseLevel(DS,1,2);
//   GetAllStudentsByPower(DS,1,&students, &size); // 140
//   free(students);
//   students=NULL;
//   RemoveStudent(DS,993);
//   RemoveStudent(DS,889);
//   AddStudent(DS,606,-2,-1);
//   AddTeam(DS,3);
//   IncreaseLevel(DS,-3,1);
//   AddStudent(DS,299,2,1);
//   IncreaseLevel(DS,0,2);
//   IncreaseLevel(DS,2,-2);
//   GetMostPowerful(DS,0,&studentId);
//   MoveStudentToTeam(DS,620,-2); // 150
//   IncreaseLevel(DS,2,3);
//   IncreaseLevel(DS,0,-1);
//   IncreaseLevel(DS,0,3);
//   GetMostPowerful(DS,3,&studentId);
//   AddStudent(DS,542,1,0);
//   GetMostPowerful(DS,3,&studentId);
//   AddStudent(DS,872,2,1);
//   IncreaseLevel(DS,-1,3);
//   GetMostPowerful(DS,1,&studentId);
//   AddTeam(DS,1); // 160
//   IncreaseLevel(DS,2,1);
//   GetAllStudentsByPower(DS,1,&students, &size);
//   free(students);
//   students=NULL;
//   MoveStudentToTeam(DS,355,0);
//   GetAllStudentsByPower(DS,0,&students, &size);
//   free(students);
//   students=NULL;
//   IncreaseLevel(DS,-3,2);
//   AddStudent(DS,459,2,3);
//   IncreaseLevel(DS,1,-3);
//   IncreaseLevel(DS,0,-2);
//   IncreaseLevel(DS,-1,3);
//   IncreaseLevel(DS,-1,2); // 170
//   RemoveStudent(DS,388);
//   IncreaseLevel(DS,-2,3);
//   IncreaseLevel(DS,3,3);
//   MoveStudentToTeam(DS,552,2);
//   GetAllStudentsByPower(DS,-1,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,0,&studentId);
//   RemoveStudent(DS,868);
//   IncreaseLevel(DS,-1,-2);
//   AddStudent(DS,820,-1,-2);
//   RemoveStudent(DS,875); // 180
//   IncreaseLevel(DS,0,-1);
//   IncreaseLevel(DS,2,-3);
//   GetMostPowerful(DS,3,&studentId);
//   RemoveStudent(DS,621);
//   GetMostPowerful(DS,1,&studentId);
//   MoveStudentToTeam(DS,486,2);
//   IncreaseLevel(DS,-3,2);
//   AddTeam(DS,1);
//   AddStudent(DS,863,2,-2);
//   AddStudent(DS,239,1,1); // 190
//   GetAllStudentsByPower(DS,-3,&students, &size);
//   free(students);
//   students=NULL;
//   MoveStudentToTeam(DS,572,2);
//   AddTeam(DS,1);
//   GetAllStudentsByPower(DS,-1,&students, &size);
//   free(students);
//   students=NULL;
//   AddTeam(DS,0);
//   MoveStudentToTeam(DS,877,0);
//   IncreaseLevel(DS,0,3);
//   GetMostPowerful(DS,-1,&studentId);
//   AddTeam(DS,0);
//   GetAllStudentsByPower(DS,0,&students, &size); // 200
//   free(students);
//   students=NULL;
//   IncreaseLevel(DS,-3,-2);
//   GetMostPowerful(DS,-2,&studentId);
//   AddTeam(DS,0);
//   AddStudent(DS,483,2,3);
//   AddStudent(DS,319,2,1);
//   AddStudent(DS,465,1,-2);
//   MoveStudentToTeam(DS,341,1);
//   RemoveStudent(DS,553);
//   AddStudent(DS,-5,1,0);
//   IncreaseLevel(DS,-3,-2); // 210
//   RemoveStudent(DS,582);
//   GetMostPowerful(DS,-1,&studentId);
//   MoveStudentToTeam(DS,730,0);
//   IncreaseLevel(DS,-1,0);
//   MoveStudentToTeam(DS,484,2);
//   AddTeam(DS,3);
//   GetAllStudentsByPower(DS,-1,&students, &size);
//   free(students);
//   students=NULL;
//   AddStudent(DS,47,-2,-1);
//   GetMostPowerful(DS,2,&studentId);
//   MoveStudentToTeam(DS,598,-2); // 220
//   IncreaseLevel(DS,-2,0);
//   IncreaseLevel(DS,2,-2);
//   GetMostPowerful(DS,1,&studentId);
//   IncreaseLevel(DS,2,-3);
//   AddStudent(DS,361,0,-3);
//   AddTeam(DS,-1);
//   GetAllStudentsByPower(DS,3,&students, &size);
//   free(students);
//   students=NULL;
//   RemoveStudent(DS,74);
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,-3,&studentId); // 230
//   GetMostPowerful(DS,1,&studentId);
//   IncreaseLevel(DS,1,2);
//   MoveStudentToTeam(DS,748,-3);
//   AddStudent(DS,659,-3,2);
//   MoveStudentToTeam(DS,193,1);
//   RemoveStudent(DS,913);
//   MoveStudentToTeam(DS,286,-2);
//   GetAllStudentsByPower(DS,-3,&students, &size);
//   free(students);
//   students=NULL;
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   IncreaseLevel(DS,0,-3); // 240
//   AddTeam(DS,3);
//   GetMostPowerful(DS,3,&studentId);
//   AddTeam(DS,-2);
//   RemoveStudent(DS,723);
//   RemoveStudent(DS,537);
//   GetMostPowerful(DS,-2,&studentId);
//   GetMostPowerful(DS,-2,&studentId);
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   AddStudent(DS,929,-2,0);
//   MoveStudentToTeam(DS,766,0); // 250
//   RemoveStudent(DS,802);
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   IncreaseLevel(DS,0,2);
//   RemoveStudent(DS,458);
//   MoveStudentToTeam(DS,470,0);
//   AddStudent(DS,175,1,1);
//   AddStudent(DS,610,0,-3);
//   MoveStudentToTeam(DS,944,-1);
//   AddTeam(DS,1);
//   AddTeam(DS,-2); // 260
//   RemoveStudent(DS,12);
//   GetMostPowerful(DS,0,&studentId);
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,-3,&studentId);
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   AddStudent(DS,386,-2,3);
//   GetMostPowerful(DS,3,&studentId);
//   AddStudent(DS,564,0,-1);
//   IncreaseLevel(DS,-3,1);
//   AddStudent(DS,46,-2,-2); // 270
//   MoveStudentToTeam(DS,273,-1);
//   IncreaseLevel(DS,1,3);
//   IncreaseLevel(DS,-3,-3);
//   IncreaseLevel(DS,-1,-1);
//   IncreaseLevel(DS,-2,1);
//   AddTeam(DS,-2);
//   IncreaseLevel(DS,0,-2);
//   AddStudent(DS,691,1,0);
//   RemoveStudent(DS,386);
//   MoveStudentToTeam(DS,391,-3); // 280
//   MoveStudentToTeam(DS,307,2);
//   GetMostPowerful(DS,0,&studentId);
//   AddTeam(DS,2);
//   RemoveStudent(DS,622);
//   MoveStudentToTeam(DS,363,-2);
//   GetMostPowerful(DS,2,&studentId);
//   IncreaseLevel(DS,0,-1);
//   GetAllStudentsByPower(DS,-1,&students, &size);
//   free(students);
//   students=NULL;
//   MoveStudentToTeam(DS,459,1);
//   RemoveStudent(DS,607); // 290
//   MoveStudentToTeam(DS,791,2);
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   IncreaseLevel(DS,0,-1);
//   MoveStudentToTeam(DS,769,-2);
//   AddStudent(DS,855,0,3);
//   GetMostPowerful(DS,1,&studentId);
//   GetMostPowerful(DS,-1,&studentId);
//   GetMostPowerful(DS,2,&studentId);
//   RemoveStudent(DS,836); // 300
//   MoveStudentToTeam(DS,18,-2);
//   RemoveStudent(DS,797);
//   RemoveStudent(DS,674);
//   RemoveStudent(DS,707);
//   AddStudent(DS,920,0,1);
//   AddStudent(DS,166,-1,-2);
//   GetAllStudentsByPower(DS,1,&students, &size);
//   free(students);
//   students=NULL;
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,3,&studentId);
//   MoveStudentToTeam(DS,176,-2); // 310
//   AddTeam(DS,-2);
//   AddTeam(DS,2);
//   AddTeam(DS,0);
//   AddTeam(DS,2);
//   GetAllStudentsByPower(DS,0,&students, &size);
//   free(students);
//   students=NULL;
//   IncreaseLevel(DS,0,-3);
//   AddTeam(DS,-1);
//   MoveStudentToTeam(DS,996,3);
//   GetMostPowerful(DS,2,&studentId);
//   GetAllStudentsByPower(DS,2,&students, &size); // 320
//   free(students);
//   students=NULL;
//   AddStudent(DS,448,1,-1);
//   RemoveStudent(DS,192);
//   IncreaseLevel(DS,-3,-1);
//   AddTeam(DS,-2);
//   GetMostPowerful(DS,-1,&studentId);
//   IncreaseLevel(DS,0,-2);
//   MoveStudentToTeam(DS,727,-2);
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   AddStudent(DS,624,3,3);
//   RemoveStudent(DS,487); // 330
//   RemoveStudent(DS,729);
//   AddTeam(DS,-3);
//   RemoveStudent(DS,961);
//   RemoveStudent(DS,355);
//   IncreaseLevel(DS,-2,-3);
//   RemoveStudent(DS,808);
//   MoveStudentToTeam(DS,289,-1);
//   AddTeam(DS,1);
//   GetAllStudentsByPower(DS,-1,&students, &size);
//   free(students);
//   students=NULL;
//   AddTeam(DS,2); // 340
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,2,&studentId);
//   AddTeam(DS,1);
//   MoveStudentToTeam(DS,43,-3);
//   AddStudent(DS,874,1,-2);
//   GetMostPowerful(DS,2,&studentId);
//   AddStudent(DS,455,3,0);
//   IncreaseLevel(DS,-1,0);
//   GetMostPowerful(DS,3,&studentId);
//   AddTeam(DS,0); // 350
//   AddTeam(DS,-3);
//   RemoveStudent(DS,210);
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   IncreaseLevel(DS,-3,3);
//   MoveStudentToTeam(DS,841,2);
//   MoveStudentToTeam(DS,93,0);
//   AddTeam(DS,2);
//   AddTeam(DS,3);
//   MoveStudentToTeam(DS,298,-2);
//   GetAllStudentsByPower(DS,-3,&students, &size); // 360
//   free(students);
//   students=NULL;
//   AddStudent(DS,216,-3,1);
//   AddTeam(DS,3);
//   IncreaseLevel(DS,-3,-3);
//   AddTeam(DS,-2);
//   GetMostPowerful(DS,0,&studentId);
//   AddTeam(DS,0);
//   AddStudent(DS,902,1,3);
//   MoveStudentToTeam(DS,510,-1);
//   GetMostPowerful(DS,-1,&studentId);
//   MoveStudentToTeam(DS,42,-2); // 370
//   AddTeam(DS,-1);
//   IncreaseLevel(DS,-2,-1);
//   AddTeam(DS,-1);
//   GetMostPowerful(DS,-3,&studentId);
//   AddTeam(DS,2);
//   AddStudent(DS,591,-1,0);
//   MoveStudentToTeam(DS,230,-1);
//   AddTeam(DS,-2);
//   AddStudent(DS,50,-3,3);
//   GetMostPowerful(DS,-2,&studentId); // 380
//   GetMostPowerful(DS,0,&studentId);
//   AddTeam(DS,2);
//   AddTeam(DS,-3);
//   AddTeam(DS,3);
//   IncreaseLevel(DS,1,3);
//   GetAllStudentsByPower(DS,-1,&students, &size);
//   free(students);
//   students=NULL;
//   RemoveStudent(DS,940);
//   MoveStudentToTeam(DS,289,3);
//   IncreaseLevel(DS,1,1);
//   IncreaseLevel(DS,1,-3); // 390
//   RemoveStudent(DS,521);
//   IncreaseLevel(DS,0,0);
//   MoveStudentToTeam(DS,440,-1);
//   IncreaseLevel(DS,-1,-3);
//   AddTeam(DS,-1);
//   GetAllStudentsByPower(DS,3,&students, &size);
//   free(students);
//   students=NULL;
//   AddTeam(DS,2);
//   GetMostPowerful(DS,-3,&studentId);
//   GetMostPowerful(DS,-3,&studentId);
//   IncreaseLevel(DS,3,-2); // 400
//   AddStudent(DS,501,0,3);
//   GetMostPowerful(DS,0,&studentId);
//   RemoveStudent(DS,253);
//   MoveStudentToTeam(DS,893,2);
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,2,&studentId);
//   MoveStudentToTeam(DS,409,2);
//   AddTeam(DS,-1);
//   GetAllStudentsByPower(DS,-1,&students, &size);
//   free(students);
//   students=NULL;
//   AddStudent(DS,692,1,0); // 410
//   GetMostPowerful(DS,0,&studentId);
//   MoveStudentToTeam(DS,226,3);
//   GetMostPowerful(DS,0,&studentId);
//   AddStudent(DS,793,3,-3);
//   RemoveStudent(DS,814);
//   GetMostPowerful(DS,2,&studentId);
//   GetAllStudentsByPower(DS,3,&students, &size);
//   free(students);
//   students=NULL;
//   AddTeam(DS,-3);
//   MoveStudentToTeam(DS,888,-3);
//   GetAllStudentsByPower(DS,1,&students, &size); // 420
//   free(students);
//   students=NULL;
//   AddStudent(DS,601,-3,1);
//   AddStudent(DS,361,3,1);
//   AddTeam(DS,2);
//   GetMostPowerful(DS,-2,&studentId);
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,-3,&studentId);
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   AddTeam(DS,0);
//   RemoveStudent(DS,302); // 430
//   MoveStudentToTeam(DS,662,0);
//   RemoveStudent(DS,426);
//   RemoveStudent(DS,436);
//   GetAllStudentsByPower(DS,3,&students, &size);
//   free(students);
//   students=NULL;
//   MoveStudentToTeam(DS,10,-2);
//   GetMostPowerful(DS,1,&studentId);
//   MoveStudentToTeam(DS,838,-1);
//   MoveStudentToTeam(DS,283,0);
//   RemoveStudent(DS,693);
//   AddTeam(DS,1); // 440
//   AddTeam(DS,0);
//   RemoveStudent(DS,175);
//   GetMostPowerful(DS,3,&studentId);
//   IncreaseLevel(DS,1,-1);
//   RemoveStudent(DS,825);
//   AddTeam(DS,0);
//   IncreaseLevel(DS,-2,3);
//   AddStudent(DS,754,-3,3);
//   RemoveStudent(DS,814);
//   MoveStudentToTeam(DS,282,-1); // 450
//   IncreaseLevel(DS,-3,0);
//   IncreaseLevel(DS,3,-3);
//   AddTeam(DS,-3);
//   MoveStudentToTeam(DS,604,1);
//   AddStudent(DS,733,-3,-2);
//   IncreaseLevel(DS,-2,-2);
//   IncreaseLevel(DS,-3,-3);
//   GetMostPowerful(DS,0,&studentId);
//   RemoveStudent(DS,420);
//   IncreaseLevel(DS,2,3); // 460
//   AddStudent(DS,946,0,-3);
//   GetAllStudentsByPower(DS,1,&students, &size);
//   free(students);
//   students=NULL;
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,-1,&studentId);
//   IncreaseLevel(DS,-1,1);
//   RemoveStudent(DS,787);
//   AddStudent(DS,59,1,2);
//   IncreaseLevel(DS,3,2);
//   GetMostPowerful(DS,0,&studentId); // 470
//   MoveStudentToTeam(DS,976,3);
//   AddTeam(DS,3);
//   GetMostPowerful(DS,1,&studentId);
//   GetMostPowerful(DS,-1,&studentId);
//   IncreaseLevel(DS,3,2);
//   GetMostPowerful(DS,3,&studentId);
//   MoveStudentToTeam(DS,697,0);
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   RemoveStudent(DS,429);
//   AddTeam(DS,-3); // 480
//   RemoveStudent(DS,643);
//   IncreaseLevel(DS,-2,1);
//   IncreaseLevel(DS,1,-2);
//   RemoveStudent(DS,222);
//   RemoveStudent(DS,603);
//   RemoveStudent(DS,786);
//   AddTeam(DS,-3);
//   AddTeam(DS,2);
//   RemoveStudent(DS,184);
//   AddStudent(DS,535,2,-2); // 490
//   IncreaseLevel(DS,-2,3);
//   IncreaseLevel(DS,3,-2);
//   GetAllStudentsByPower(DS,-3,&students, &size);
//   free(students);
//   students=NULL;
//   AddTeam(DS,-1);
//   AddStudent(DS,854,-1,2);
//   AddTeam(DS,1);
//   MoveStudentToTeam(DS,736,-3);
//   AddTeam(DS,0);
//   GetAllStudentsByPower(DS,-3,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,-1,&studentId); // 500
//   MoveStudentToTeam(DS,169,3);
//   GetAllStudentsByPower(DS,-3,&students, &size);
//   free(students);
//   students=NULL;
//   AddTeam(DS,1);
//   RemoveStudent(DS,501);
//   IncreaseLevel(DS,-1,-1);
//   GetMostPowerful(DS,3,&studentId);
//   RemoveStudent(DS,452);
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   AddTeam(DS,-3);
//   AddTeam(DS,3); // 510
//   RemoveStudent(DS,627);
//   AddTeam(DS,-1);
//   IncreaseLevel(DS,-3,1);
//   IncreaseLevel(DS,-1,-1);
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   AddTeam(DS,3);
//   GetMostPowerful(DS,3,&studentId);
//   AddStudent(DS,912,-3,1);
//   IncreaseLevel(DS,-2,0);
//   AddTeam(DS,0); // 520
//   AddStudent(DS,118,0,2);
//   RemoveStudent(DS,393);
//   GetMostPowerful(DS,-3,&studentId);
//   GetMostPowerful(DS,2,&studentId);
//   AddTeam(DS,-2);
//   GetMostPowerful(DS,1,&studentId);
//   RemoveStudent(DS,112);
//   RemoveStudent(DS,292);
//   MoveStudentToTeam(DS,32,0);
//   GetAllStudentsByPower(DS,3,&students, &size); // 530
//   free(students);
//   students=NULL;
//   AddTeam(DS,-1);
//   MoveStudentToTeam(DS,479,3);
//   AddStudent(DS,437,0,-3);
//   MoveStudentToTeam(DS,299,3);
//   RemoveStudent(DS,616);
//   IncreaseLevel(DS,-2,1);
//   GetMostPowerful(DS,0,&studentId);
//   AddTeam(DS,-3);
//   AddStudent(DS,165,-2,0);
//   RemoveStudent(DS,32); // 540
//   GetMostPowerful(DS,-3,&studentId);
//   AddTeam(DS,-2);
//   IncreaseLevel(DS,3,-2);
//   IncreaseLevel(DS,1,3);
//   IncreaseLevel(DS,2,2);
//   GetAllStudentsByPower(DS,-1,&students, &size);
//   free(students);
//   students=NULL;
//   AddTeam(DS,2);
//   AddTeam(DS,-2);
//   AddTeam(DS,3);
//   MoveStudentToTeam(DS,518,-1); // 550
//   IncreaseLevel(DS,3,-3);
//   GetMostPowerful(DS,-1,&studentId);
//   GetAllStudentsByPower(DS,0,&students, &size);
//   free(students);
//   students=NULL;
//   RemoveStudent(DS,151);
//   IncreaseLevel(DS,-2,-3);
//   GetMostPowerful(DS,1,&studentId);
//   GetMostPowerful(DS,-2,&studentId);
//   AddTeam(DS,-2);
//   AddTeam(DS,-1);
//   AddTeam(DS,-1); // 560
//   RemoveStudent(DS,530);
//   MoveStudentToTeam(DS,740,-3);
//   IncreaseLevel(DS,-1,1);
//   RemoveStudent(DS,273);
//   AddStudent(DS,141,3,-1);
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   AddTeam(DS,-2);
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   AddTeam(DS,0);
//   GetAllStudentsByPower(DS,0,&students, &size); // 570
//   free(students);
//   students=NULL;
//   IncreaseLevel(DS,1,1);
//   GetMostPowerful(DS,-3,&studentId);
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,-3,&studentId);
//   GetMostPowerful(DS,-2,&studentId);
//   AddStudent(DS,369,-3,2);
//   AddStudent(DS,394,2,2);
//   GetMostPowerful(DS,1,&studentId);
//   AddTeam(DS,3);
//   RemoveStudent(DS,644); // 580
//   GetMostPowerful(DS,-2,&studentId);
//   AddTeam(DS,1);
//   MoveStudentToTeam(DS,390,3);
//   AddTeam(DS,3);
//   GetMostPowerful(DS,3,&studentId);
//   AddTeam(DS,0);
//   AddStudent(DS,292,2,0);
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   AddStudent(DS,758,-3,-3);
//   GetAllStudentsByPower(DS,3,&students, &size); // 590
//   free(students);
//   students=NULL;
//   AddTeam(DS,2);
//   MoveStudentToTeam(DS,640,-2);
//   MoveStudentToTeam(DS,730,-1);
//   MoveStudentToTeam(DS,557,-1);
//   AddTeam(DS,2);
//   AddStudent(DS,443,0,-3);
//   GetMostPowerful(DS,3,&studentId);
//   MoveStudentToTeam(DS,690,-2);
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,2,&studentId); // 600
//   AddTeam(DS,-2);
//   GetMostPowerful(DS,3,&studentId);
//   RemoveStudent(DS,116);
//   MoveStudentToTeam(DS,507,-3);
//   GetMostPowerful(DS,2,&studentId);
//   AddStudent(DS,678,1,0);
//   RemoveStudent(DS,825);
//   GetAllStudentsByPower(DS,3,&students, &size);
//   free(students);
//   students=NULL;
//   IncreaseLevel(DS,-2,2);
//   AddTeam(DS,0); // 610
//   AddStudent(DS,80,-3,3);
//   MoveStudentToTeam(DS,464,0);
//   GetAllStudentsByPower(DS,-1,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,1,&studentId);
//   GetMostPowerful(DS,1,&studentId);
//   IncreaseLevel(DS,-1,3);
//   AddTeam(DS,-2);
//   MoveStudentToTeam(DS,983,1);
//   GetAllStudentsByPower(DS,-3,&students, &size);
//   free(students);
//   students=NULL;
//   RemoveStudent(DS,440); // 620
//   MoveStudentToTeam(DS,633,2);
//   MoveStudentToTeam(DS,705,0);
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   GetAllStudentsByPower(DS,0,&students, &size);
//   free(students);
//   students=NULL;
//   RemoveStudent(DS,157);
//   RemoveStudent(DS,448);
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   RemoveStudent(DS,342);
//   GetAllStudentsByPower(DS,0,&students, &size);
//   free(students);
//   students=NULL;
//   AddStudent(DS,25,3,2); // 630
//   RemoveStudent(DS,907);
//   GetAllStudentsByPower(DS,-1,&students, &size);
//   free(students);
//   students=NULL;
//   AddTeam(DS,0);
//   AddStudent(DS,41,0,-3);
//   AddTeam(DS,0);
//   AddTeam(DS,-1);
//   RemoveStudent(DS,934);
//   RemoveStudent(DS,955);
//   MoveStudentToTeam(DS,882,2);
//   MoveStudentToTeam(DS,626,1); // 640
//   MoveStudentToTeam(DS,522,-1);
//   AddTeam(DS,-2);
//   GetAllStudentsByPower(DS,0,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,-2,&studentId);
//   GetAllStudentsByPower(DS,-3,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,-2,&studentId);
//   IncreaseLevel(DS,-2,3);
//   GetAllStudentsByPower(DS,-1,&students, &size);
//   free(students);
//   students=NULL;
//   AddTeam(DS,-1);
//   AddTeam(DS,3); // 650
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   MoveStudentToTeam(DS,884,-1);
//   AddStudent(DS,885,2,-2);
//   AddStudent(DS,568,-1,1);
//   RemoveStudent(DS,79);
//   RemoveStudent(DS,856);
//   GetAllStudentsByPower(DS,1,&students, &size);
//   free(students);
//   students=NULL;
//   RemoveStudent(DS,911);
//   IncreaseLevel(DS,-1,-2);
//   GetAllStudentsByPower(DS,-3,&students, &size); // 660
//   free(students);
//   students=NULL;
//   IncreaseLevel(DS,-3,1);
//   AddStudent(DS,707,-3,-1);
//   AddStudent(DS,460,3,3);
//   MoveStudentToTeam(DS,276,-3);
//   RemoveStudent(DS,458);
//   GetAllStudentsByPower(DS,0,&students, &size);
//   free(students);
//   students=NULL;
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   AddStudent(DS,766,-1,3);
//   MoveStudentToTeam(DS,344,3);
//   IncreaseLevel(DS,-3,1); // 670
//   GetAllStudentsByPower(DS,1,&students, &size);
//   free(students);
//   students=NULL;
//   GetAllStudentsByPower(DS,3,&students, &size);
//   free(students);
//   students=NULL;
//   IncreaseLevel(DS,0,1);
//   AddStudent(DS,360,-3,-3);
//   GetAllStudentsByPower(DS,0,&students, &size);
//   free(students);
//   students=NULL;
//   IncreaseLevel(DS,-2,2);
//   GetAllStudentsByPower(DS,3,&students, &size);
//   free(students);
//   students=NULL;
//   IncreaseLevel(DS,-3,3);
//   IncreaseLevel(DS,1,-2);
//   RemoveStudent(DS,195); // 680
//   AddTeam(DS,1);
//   MoveStudentToTeam(DS,786,-3);
//   RemoveStudent(DS,87);
//   AddStudent(DS,618,2,2);
//   IncreaseLevel(DS,-1,0);
//   AddStudent(DS,978,-3,0);
//   GetAllStudentsByPower(DS,3,&students, &size);
//   free(students);
//   students=NULL;
//   GetAllStudentsByPower(DS,0,&students, &size);
//   free(students);
//   students=NULL;
//   AddStudent(DS,819,1,1);
//   IncreaseLevel(DS,-1,-3); // 690
//   RemoveStudent(DS,627);
//   AddStudent(DS,-5,1,-2);
//   MoveStudentToTeam(DS,692,2);
//   IncreaseLevel(DS,-2,-1);
//   AddTeam(DS,3);
//   IncreaseLevel(DS,-3,-2);
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   MoveStudentToTeam(DS,327,0);
//   RemoveStudent(DS,551);
//   RemoveStudent(DS,319); // 700
//   IncreaseLevel(DS,0,-3);
//   IncreaseLevel(DS,2,-1);
//   AddStudent(DS,65,0,3);
//   GetAllStudentsByPower(DS,-3,&students, &size);
//   free(students);
//   students=NULL;
//   GetAllStudentsByPower(DS,1,&students, &size);
//   free(students);
//   students=NULL;
//   GetAllStudentsByPower(DS,0,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,2,&studentId);
//   AddStudent(DS,350,3,-2);
//   AddStudent(DS,834,0,2);
//   AddStudent(DS,628,1,3); // 710
//   GetAllStudentsByPower(DS,0,&students, &size);
//   free(students);
//   students=NULL;
//   MoveStudentToTeam(DS,697,2);
//   AddStudent(DS,254,3,-2);
//   GetMostPowerful(DS,-1,&studentId);
//   AddTeam(DS,-1);
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   MoveStudentToTeam(DS,76,-1);
//   IncreaseLevel(DS,-2,1);
//   AddStudent(DS,180,2,1);
//   RemoveStudent(DS,676); // 720
//   RemoveStudent(DS,485);
//   AddStudent(DS,723,1,-2);
//   RemoveStudent(DS,158);
//   AddTeam(DS,-1);
//   AddTeam(DS,2);
//   MoveStudentToTeam(DS,388,1);
//   RemoveStudent(DS,618);
//   AddTeam(DS,2);
//   IncreaseLevel(DS,0,-1);
//   AddTeam(DS,3); // 730
//   AddStudent(DS,380,-1,1);
//   GetMostPowerful(DS,-1,&studentId);
//   RemoveStudent(DS,484);
//   GetMostPowerful(DS,-3,&studentId);
//   RemoveStudent(DS,910);
//   GetMostPowerful(DS,2,&studentId);
//   AddStudent(DS,-9,1,-3);
//   AddStudent(DS,900,-3,2);
//   IncreaseLevel(DS,0,0);
//   AddTeam(DS,1); // 740
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   MoveStudentToTeam(DS,801,1);
//   RemoveStudent(DS,862);
//   AddTeam(DS,-3);
//   AddStudent(DS,992,-1,1);
//   GetAllStudentsByPower(DS,-3,&students, &size);
//   free(students);
//   students=NULL;
//   GetAllStudentsByPower(DS,-1,&students, &size);
//   free(students);
//   students=NULL;
//   RemoveStudent(DS,145);
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   AddStudent(DS,623,-3,-3); // 750
//   MoveStudentToTeam(DS,61,3);
//   RemoveStudent(DS,295);
//   MoveStudentToTeam(DS,884,3);
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   MoveStudentToTeam(DS,290,3);
//   AddStudent(DS,4,-2,3);
//   GetAllStudentsByPower(DS,-1,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,-3,&studentId);
//   RemoveStudent(DS,270);
//   IncreaseLevel(DS,1,-2); // 760
//   GetMostPowerful(DS,3,&studentId);
//   RemoveStudent(DS,682);
//   GetAllStudentsByPower(DS,-3,&students, &size);
//   free(students);
//   students=NULL;
//   MoveStudentToTeam(DS,858,-1);
//   MoveStudentToTeam(DS,62,3);
//   MoveStudentToTeam(DS,853,-3);
//   RemoveStudent(DS,208);
//   IncreaseLevel(DS,-3,-3);
//   RemoveStudent(DS,724);
//   AddStudent(DS,196,-1,-1); // 770
//   MoveStudentToTeam(DS,576,3);
//   GetMostPowerful(DS,-1,&studentId);
//   MoveStudentToTeam(DS,681,-3);
//   IncreaseLevel(DS,1,-3);
//   MoveStudentToTeam(DS,-3,-2);
//   RemoveStudent(DS,808);
//   RemoveStudent(DS,349);
//   AddTeam(DS,-3);
//   MoveStudentToTeam(DS,705,3);
//   AddTeam(DS,2); // 780
//   MoveStudentToTeam(DS,263,0);
//   GetAllStudentsByPower(DS,-1,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,-2,&studentId);
//   MoveStudentToTeam(DS,77,-1);
//   RemoveStudent(DS,752);
//   RemoveStudent(DS,288);
//   MoveStudentToTeam(DS,622,2);
//   AddStudent(DS,75,-3,-3);
//   IncreaseLevel(DS,3,-3);
//   AddStudent(DS,519,1,-2); // 790
//   GetAllStudentsByPower(DS,-3,&students, &size);
//   free(students);
//   students=NULL;
//   AddTeam(DS,0);
//   MoveStudentToTeam(DS,486,3);
//   AddStudent(DS,652,-2,1);
//   MoveStudentToTeam(DS,384,1);
//   GetAllStudentsByPower(DS,-3,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,-3,&studentId);
//   AddStudent(DS,164,0,3);
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   AddTeam(DS,1); // 800
//   RemoveStudent(DS,849);
//   MoveStudentToTeam(DS,852,0);
//   GetMostPowerful(DS,3,&studentId);
//   AddStudent(DS,546,-2,-1);
//   IncreaseLevel(DS,0,-3);
//   IncreaseLevel(DS,0,-2);
//   AddTeam(DS,2);
//   GetAllStudentsByPower(DS,-1,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,1,&studentId);
//   AddStudent(DS,355,2,-1); // 810
//   AddTeam(DS,-3);
//   IncreaseLevel(DS,-2,-1);
//   MoveStudentToTeam(DS,778,-2);
//   GetMostPowerful(DS,-2,&studentId);
//   AddStudent(DS,590,0,2);
//   IncreaseLevel(DS,0,0);
//   AddTeam(DS,-1);
//   AddStudent(DS,482,-2,-1);
//   GetAllStudentsByPower(DS,3,&students, &size);
//   free(students);
//   students=NULL;
//   AddStudent(DS,463,1,2); // 820
//   GetAllStudentsByPower(DS,3,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,-2,&studentId);
//   RemoveStudent(DS,968);
//   AddTeam(DS,0);
//   AddStudent(DS,142,2,2);
//   AddStudent(DS,878,1,3);
//   MoveStudentToTeam(DS,369,-3);
//   RemoveStudent(DS,89);
//   AddTeam(DS,1);
//   MoveStudentToTeam(DS,57,3); // 830
//   GetMostPowerful(DS,3,&studentId);
//   MoveStudentToTeam(DS,502,1);
//   IncreaseLevel(DS,-1,1);
//   IncreaseLevel(DS,3,-2);
//   MoveStudentToTeam(DS,46,-2);
//   GetMostPowerful(DS,3,&studentId);
//   GetMostPowerful(DS,0,&studentId);
//   GetAllStudentsByPower(DS,1,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,-3,&studentId);
//   GetAllStudentsByPower(DS,-1,&students, &size); // 840
//   free(students);
//   students=NULL;
//   AddTeam(DS,0);
//   GetMostPowerful(DS,2,&studentId);
//   AddStudent(DS,966,2,-1);
//   AddTeam(DS,-3);
//   AddTeam(DS,2);
//   AddTeam(DS,3);
//   GetAllStudentsByPower(DS,1,&students, &size);
//   free(students);
//   students=NULL;
//   AddTeam(DS,1);
//   GetMostPowerful(DS,-2,&studentId);
//   GetAllStudentsByPower(DS,1,&students, &size); // 850
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,2,&studentId);
//   IncreaseLevel(DS,1,1);
//   GetMostPowerful(DS,3,&studentId);
//   IncreaseLevel(DS,2,0);
//   AddStudent(DS,426,3,3);
//   AddStudent(DS,768,3,-1);
//   AddStudent(DS,642,0,-3);
//   GetMostPowerful(DS,2,&studentId);
//   IncreaseLevel(DS,3,-2);
//   MoveStudentToTeam(DS,222,0); // 860
//   AddTeam(DS,3);
//   RemoveStudent(DS,360);
//   IncreaseLevel(DS,0,-3);
//   RemoveStudent(DS,913);
//   MoveStudentToTeam(DS,670,-1);
//   GetMostPowerful(DS,-2,&studentId);
//   AddStudent(DS,544,1,3);
//   AddTeam(DS,0);
//   MoveStudentToTeam(DS,324,0);
//   AddStudent(DS,381,-2,-2); // 870
//   RemoveStudent(DS,519);
//   GetMostPowerful(DS,-3,&studentId);
//   IncreaseLevel(DS,-3,1);
//   AddStudent(DS,897,-1,2);
//   GetMostPowerful(DS,-3,&studentId);
//   MoveStudentToTeam(DS,733,3);
//   GetMostPowerful(DS,2,&studentId);
//   AddTeam(DS,-1);
//   GetAllStudentsByPower(DS,-1,&students, &size);
//   free(students);
//   students=NULL;
//   RemoveStudent(DS,811); // 880
//   MoveStudentToTeam(DS,995,0);
//   MoveStudentToTeam(DS,691,-2);
//   GetMostPowerful(DS,-1,&studentId);
//   AddTeam(DS,1);
//   RemoveStudent(DS,443);
//   GetMostPowerful(DS,3,&studentId);
//   AddStudent(DS,96,2,-2);
//   MoveStudentToTeam(DS,567,-1);
//   MoveStudentToTeam(DS,590,3);
//   AddTeam(DS,-1); // 890
//   GetAllStudentsByPower(DS,2,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,-2,&studentId);
//   GetAllStudentsByPower(DS,0,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,1,&studentId);
//   GetMostPowerful(DS,-1,&studentId);
//   RemoveStudent(DS,601);
//   AddStudent(DS,755,3,-1);
//   IncreaseLevel(DS,0,3);
//   AddTeam(DS,3);
//   MoveStudentToTeam(DS,191,1); // 900
//   AddStudent(DS,738,0,0);
//   AddStudent(DS,991,0,1);
//   MoveStudentToTeam(DS,977,-3);
//   AddStudent(DS,100,3,-1);
//   MoveStudentToTeam(DS,122,0);
//   GetAllStudentsByPower(DS,0,&students, &size);
//   free(students);
//   students=NULL;
//   IncreaseLevel(DS,1,-1);
//   GetMostPowerful(DS,-3,&studentId);
//   GetMostPowerful(DS,-3,&studentId);
//   GetMostPowerful(DS,-3,&studentId); // 910
//   GetAllStudentsByPower(DS,-2,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,2,&studentId);
//   IncreaseLevel(DS,-3,0);
//   IncreaseLevel(DS,0,-2);
//   RemoveStudent(DS,8);
//   RemoveStudent(DS,942);
//   MoveStudentToTeam(DS,955,-3);
//   AddTeam(DS,1);
//   RemoveStudent(DS,235);
//   MoveStudentToTeam(DS,519,0); // 920
//   IncreaseLevel(DS,-1,1);
//   AddTeam(DS,-1);
//   GetAllStudentsByPower(DS,3,&students, &size);
//   free(students);
//   students=NULL;
//   RemoveStudent(DS,578);
//   AddTeam(DS,0);
//   GetMostPowerful(DS,-2,&studentId);
//   RemoveStudent(DS,368);
//   IncreaseLevel(DS,-3,1);
//   IncreaseLevel(DS,-1,0);
//   GetAllStudentsByPower(DS,-1,&students, &size); // 930
//   free(students);
//   students=NULL;
//   AddStudent(DS,613,0,2);
//   RemoveStudent(DS,697);
//   RemoveStudent(DS,609);
//   AddStudent(DS,186,3,3);
//   GetMostPowerful(DS,0,&studentId);
//   AddTeam(DS,2);
//   AddTeam(DS,2);
//   IncreaseLevel(DS,2,-2);
//   RemoveStudent(DS,590);
//   GetMostPowerful(DS,1,&studentId); // 940
//   AddTeam(DS,3);
//   AddTeam(DS,-2);
//   GetAllStudentsByPower(DS,-3,&students, &size);
//   free(students);
//   students=NULL;
//   RemoveStudent(DS,928);
//   GetMostPowerful(DS,3,&studentId);
//   MoveStudentToTeam(DS,451,2);
//   IncreaseLevel(DS,1,2);
//   MoveStudentToTeam(DS,273,1);
//   AddStudent(DS,201,-1,-3);
//   MoveStudentToTeam(DS,561,1); // 950
//   AddStudent(DS,920,2,0);
//   AddTeam(DS,-1);
//   AddTeam(DS,0);
//   GetAllStudentsByPower(DS,-3,&students, &size);
//   free(students);
//   students=NULL;
//   MoveStudentToTeam(DS,249,1);
//   RemoveStudent(DS,68);
//   IncreaseLevel(DS,0,-2);
//   MoveStudentToTeam(DS,127,-2);
//   GetAllStudentsByPower(DS,1,&students, &size);
//   free(students);
//   students=NULL;
//   GetMostPowerful(DS,0,&studentId); // 960
//   AddTeam(DS,-3);
//   AddTeam(DS,-3);
//   AddTeam(DS,-3);
//   IncreaseLevel(DS,1,3);
//   GetMostPowerful(DS,-1,&studentId);
//   AddStudent(DS,202,-2,-3);
//   AddStudent(DS,925,-2,-1);
//   MoveStudentToTeam(DS,576,2);
//   IncreaseLevel(DS,2,-1);
//   GetMostPowerful(DS,-3,&studentId); // 970
//   GetMostPowerful(DS,-2,&studentId);
//   AddStudent(DS,948,0,3);
//   MoveStudentToTeam(DS,718,-3);
//   AddTeam(DS,2);
//   AddStudent(DS,501,3,3);
//   IncreaseLevel(DS,2,-2);
//   AddTeam(DS,-2);
//   MoveStudentToTeam(DS,281,3);
//   MoveStudentToTeam(DS,591,-2);
//   AddTeam(DS,0); // 980
//   GetMostPowerful(DS,0,&studentId);
//   MoveStudentToTeam(DS,453,-1);
//   AddTeam(DS,-2);
//   AddStudent(DS,468,1,2);
//   AddTeam(DS,-2);
//   AddStudent(DS,336,-3,-2);
//   AddStudent(DS,792,-2,-3);
//   RemoveStudent(DS,400);
//   IncreaseLevel(DS,2,-1);
//   AddTeam(DS,1); // 990
//   IncreaseLevel(DS,1,3);
//   IncreaseLevel(DS,-1,-3);
//   MoveStudentToTeam(DS,477,2);
//   AddStudent(DS,554,-3,-2);
//   MoveStudentToTeam(DS,529,0);
//   AddTeam(DS,-1);
//   RemoveStudent(DS,481);
//   GetMostPowerful(DS,-3,&studentId);
//   AddTeam(DS,2);
//   MoveStudentToTeam(DS,321,-3); // 1000
//   GetMostPowerful(DS,2,&studentId);
//   Quit(&DS);
//}
